### ISSUE TITLE
missing file ?

### ISSUE THREAD

**Issue by bastianh** [AlanQuatermain/go-tmbundle#6]
/Users/user/Library/Application Support/TextMate/Bundles/go.tmbundle/Support/goerrs.rb:3:in `require': no such file to load -- /Applications/TextMate.app/Contents/SharedSupport/Support/lib/Build

I don't have a Build.rb in this directory.. are there any dependencies to other bundles?

**Comment by thrashr888** [comment]
I have the same issue:

``` html
/Users/user/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/goerrs.rb:3:in 'require': no such file to load -- /Applications/TextMate.app/Contents/SharedSupport/Support/lib/Builder (LoadError) from /Users/user/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/goerrs.rb:3 from /Users/user/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/gomate.rb:5:in 'require' from /Users/user/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/gomate.rb:5 from /tmp/temp_textmate.rSHpsG:3:in 'require' from /tmp/temp_textmate.rSHpsG:3
```

I tried commenting out `goerrs.rb:line 3` and then got another error in the Textmate run window:

``` html
<h3 class="error">Couldn't find 6g</h3>

<p>Locations searched:</p>
<p><pre>
/Users/user/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/bin
/Applications/TextMate.app/Contents/SharedSupport/Support/bin/CocoaDialog.app/Contents/MacOS
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/TextMate.app/Contents/SharedSupport/Support/bin
</pre></p>
```

I then `ln -s` the `6g` and `6l` files into `/Users/user/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/bin/` and got a bunch of other errors.

``` html
/Users/user/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/goerrs.rb:24:in `link_errs': uninitialized constant Go::Builder (NameError) from /Users/thrashr888/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/gomate.rb:16:in `gomate' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/executor.rb:116:in `call' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/executor.rb:116:in `run' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/io.rb:44:in `call' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/io.rb:44:in `exhaust' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/io.rb:44:in `each_line' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/io.rb:44:in `exhaust' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/process.rb:227:in `run' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/executor.rb:140:in `run' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/executor.rb:228:in `process_output_wrapper' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/executor.rb:139:in `run' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/htmloutput.rb:69:in `call' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/htmloutput.rb:69:in `show' from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/tm/executor.rb:110:in `run' from /Users/user/Library/Application Support/TextMate/Bundles/Go.tmbundle/Support/gomate.rb:15:in `gomate' from /tmp/temp_textmate.EiJpqj:5
```

...and now I give up. :(

**Comment by iMax-pp** [comment]
I have the same issue.

It seems like, in the latest release of TextMate, the `Builder.rb` script has been removed from `SharedSupport/Support/lib`.
Hopefully, the PHP bundle still contains this file. So a simple workaround is to `ln -s` the `Builder.rb` file from the PHP bundle (like following).

```
ln -s /Applications/TextMate.app/Contents/SharedSupport/Bundles/PHP.tmbundle/Support/lib/Builder.rb /Applications/TextMate.app/Contents/SharedSupport/Support/lib/Builder.rb
```

A better solution might be to include the file directly in Go bundle.

**Comment by DaleLJefferson** [comment]
Same issue with Textmate Version 1.5.10 (1631) on Mac OS lion
